# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.IntegerField()),
                ('amount', models.IntegerField(default=1)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.IngredientAmount'),
        ),
    ]
