# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20160909_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
