# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20160920_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
