# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20160920_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='primary_id',
            new_name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='ingredientname',
            name='primary_id',
        ),
    ]
