# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160920_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 19, 57, 2, 62500, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
