# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
